global using System.Collections.Immutable;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Localization;
global using Microsoft.Extensions.Logging;
global using Microsoft.Extensions.Options;
global using PelotonIDE.DataContracts;
global using PelotonIDE.DataContracts.Serialization;
global using PelotonIDE.Models;
global using PelotonIDE.Presentation;
global using PelotonIDE.Services.Caching;
global using PelotonIDE.Services.Endpoints;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
